[package]
name = "rustbot"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.14.0"
axum = "0.8.4"
axum-cookie = "0.2.3"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version="0.6.6", features = ["fs"] }
