name: Rustbot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clippy check
      run: cargo clippy -- -D warnings
    - name: Install Python dependencies
      run: pip install -r python_requirements.txt
    - name: tests
      run: python3 integration_tests.py
